package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SENSOR_CONFIG".
 */
public class SensorConfig {

    private Long ID;
    private String Name;
    private Boolean State;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SensorConfig() {
    }

    public SensorConfig(Long ID, String Name, Boolean State) {
        this.ID = ID;
        this.Name = Name;
        this.State = State;
    }

    public Long getID() {
        return ID;
    }

    public void setID(Long ID) {
        this.ID = ID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Boolean getState() {
        return State;
    }

    public void setState(Boolean State) {
        this.State = State;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
